# Generated by Django 5.1.6 on 2025-07-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_barcode_product_exp_date_product_mfg_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default='0'),
        ),
    ]
