# Generated by Django 5.1.6 on 2025-07-18 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_at_order_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
